In [1]:
import numpy as np

In [5]:
sample_array=np.array([1, 2, 3])

In [6]:
sample_array

array([1, 2, 3])

In [7]:
sample_array.dtype

dtype('int32')

In [8]:
ones=np.ones((2,3))

In [9]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
ones.dtype

dtype('float64')

In [11]:
type(ones)

numpy.ndarray

In [12]:
zeros=np.zeros((2,3))

In [13]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
range_array=np.arange(0,10,2)

In [15]:
range_array

array([0, 2, 4, 6, 8])

In [17]:
random_array=np.random.randint(0,10,size=(3,5))

In [18]:
random_array

array([[7, 3, 8, 1, 8],
       [3, 3, 4, 4, 3],
       [5, 1, 9, 0, 8]])

In [19]:
random_array.size

15

In [20]:
random_array.shape

(3, 5)

In [21]:
np.random.random((5,3))

array([[0.83272203, 0.97628359, 0.1486201 ],
       [0.44072044, 0.33768043, 0.96095596],
       [0.11677826, 0.99173931, 0.57962016],
       [0.10376352, 0.27159546, 0.73845793],
       [0.46320894, 0.96279255, 0.42404069]])

In [22]:
random_array_2=np.random.random((5,3))

In [23]:
random_array_2

array([[0.04779374, 0.03681113, 0.6825669 ],
       [0.19932315, 0.69734563, 0.567061  ],
       [0.21665959, 0.36346526, 0.46898909],
       [0.40656941, 0.38578244, 0.32979722],
       [0.21015542, 0.92742389, 0.10787646]])

In [24]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3=np.random.rand(5,3)

In [28]:
random_array_3

array([[0.68026823, 0.77019554, 0.365644  ],
       [0.18207256, 0.05218193, 0.38298974],
       [0.19530579, 0.24560166, 0.93859313],
       [0.77519763, 0.9101291 , 0.9635917 ],
       [0.72247578, 0.02234706, 0.08315181]])